version: "3"
services:
  db:
    image: mongo
    volumes:
      - ${MONGODB_VOLUME}
    ports:
      - 27018:27017
    container_name: mongo
  
  service:
    image: daxnet/weshareservice
    links:
      - db
    depends_on:
      - db
    ports:
      - 9023:9023
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:9023
    container_name: weshareservice

  web:
    image: daxnet/weshareweb
    links:
      - service
    depends_on:
      - service
    ports:
      - ${WEB_PORT}:80
    container_name: weshareweb
